WebWallet/Wallet.Web/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Wallet.Core.Dtos.Account;
using Wallet.Core.Models;
using Wallet.Core.QueryParameters;
using Wallet.Service.Interfaces;
using Wallet.Web.Filters;
using Wallet.Web.Mappers;
using Wallet.Web.ViewModels.Accounts;

namespace Wallet.Web.Controllers
{
    [Authorize]
    [CustomExceptionFilter]
    public class AccountsController : Controller
    {
        private readonly IUsersService _usersService;
        private readonly IAccountService _accountService;
        private readonly AccountMapper _accountMapper;

        public AccountsController(IUsersService usersService, IAccountService accountService, AccountMapper accountMapper)
        {
            this._usersService = usersService;
            this._accountService = accountService;
            this._accountMapper = accountMapper;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] AccountQueryParameters filterParameters)
        {

            User user = await this._usersService.GetByUserNameAsync(User.Identity.Name);
            PaginatedList<Account> accounts = await this._accountService.SearchByAsync(filterParameters, user);
            accounts.AccountFilterParameters = filterParameters;

            return View(accounts);
        }

        [HttpPost]
        [Route("Accounts/Delete")]
        public async Task<IActionResult> Delete(int accountId)
        {
            User user = await this._usersService.GetByUsernameWithAccountsAsync(User.Identity.Name);
            await this._accountService.DeleteAsync(accountId, user);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("Accounts/Create")]
        public async Task<IActionResult> Create(CreateAccountViewModel viewModel)
        {
            User user = await this._usersService.GetByUsernameWithAccountsAsync(User.Identity.Name);
            Account accountToCreate = this._accountMapper.Map(viewModel);
            await this._accountService.CreateAsync(accountToCreate, user);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("Accounts/Update")]
        public async Task<IActionResult> Update(AccountUpdateDto viewModel)
        {
            User user = await this._usersService.GetByUsernameWithAccountsAsync(User.Identity.Name);
            await this._accountService.UpdateAsync(viewModel, user);

            return RedirectToAction(nameof(Index));
        }
    }
}

WebWallet/Wallet.Web/Controllers/BankCardsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Wallet.Core.Dtos.BankCard;
using Wallet.Core.Models;
using Wallet.Helpers.Еxceptions;
using Wallet.Service.Interfaces;
using Wallet.Web.Mappers;
using Wallet.Web.ViewModels.BankCards;

namespace Wallet.Web.Controllers
{
    [Authorize]
    public class BankCardsController : Controller
    {
        IBankCardService _bankCardService;
        IUsersService _usersService;
        BankCardMapper _bankCardMapper;
        public BankCardsController(IUsersService usersService, IBankCardService bankCardService, BankCardMapper bankCardMapper)
        {
            this._bankCardService = bankCardService;
            this._usersService = usersService;
            this._bankCardMapper = bankCardMapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            User user = await this._usersService.GetByUserNameAsync(User.Identity.Name);
            user = await this._usersService.GetByIdWithBankCardsAsync(user.Id);
            UserWithCardsViewModel viewModel = this._bankCardMapper.Map(user.BankCards);

            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int bankCardId)
        {
            try
            {
                User user = await this._usersService.GetByUserNameAsync(User.Identity.Name);
                user = await this._usersService.GetByIdWithBankCardsAsync(user.Id);
                await this._bankCardService.DeleteAsync(bankCardId, user);

                return RedirectToAction("Index");
            }
            catch (UnauthorizedOperationException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 401, message = ex.Message });
            }
        }

        [HttpPost]
        [Route("BankCards/UpdateAsync")]
        public async Task<IActionResult> UpdateAsync(BankCardUpdateDto cardUpdates)
        {
            try
            {
                User user = await this._usersService.GetByUserNameAsync(User.Identity.Name);
                BankCard existingCard = await this._bankCardService.UpdateAsync(cardUpdates, user);

                return RedirectToAction("Index");
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 400, message = ex.Message });
            }
            catch (UnauthorizedOperationException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 401, message = ex.Message });
            }
        }

        [HttpPost]
        [Route("BankCards/CreateAsync")]
        public async Task<IActionResult> CreateAsync(CreateCardViewModel cardModel)
        {
            try
            {
                User user = await this._usersService.GetByUserNameAsync(User.Identity.Name);
                BankCard cardToCreate = this._bankCardMapper.Map(cardModel, user.Id);
                await this._bankCardService.CreateAsync(cardToCreate, user);

                return RedirectToAction("Index");
            }
            catch (InvalidOperationException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 400, message = ex.Message });
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 400, message = ex.Message });
            }
            catch (UnauthorizedOperationException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 401, message = ex.Message });
            }
        }
    }
}

WebWallet/Wallet.Web/Controllers/CurrenciesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Wallet.Helpers.Еxceptions;
using Wallet.Service.Interfaces;
using Wallet.Web.ViewModels.Currencies;

namespace Wallet.Web.Controllers
{
    [Authorize]
    public class CurrenciesController : Controller
    {
        ICurrencyService _currencyService;

        public CurrenciesController (ICurrencyService currencyService)
        {
            this._currencyService = currencyService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string currencyBase = "USD")
        {
           var result = await this._currencyService.GetAllWithRatesAsync(currencyBase);
            
            return this.View(result);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CreateCurrencyViewModel viewModel)
        {
            try
            {
                await this._currencyService.CreateAsync(viewModel.Id, viewModel.Name);

                return RedirectToAction("Index");
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 400, message = ex.Message });
            }
            catch (DuplicateEntityException ex)
            {
                return RedirectToAction("Index", "Error", new { id = 400, message = ex.Message });
            }
        }
    }
}

WebWallet/Wallet.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager
@using Wallet.Web.HelpersWeb

<!DOCTYPE html>
<html data-bs-theme="light" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Wallet.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap">
    <link rel="stylesheet" href="~/lib/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href = "~/css/bankCards.css"/>
     <link rel="stylesheet" href = "~/css/Accounts.css"/>
     <link rel="stylesheet" href = "~/css/Currencies.css"/>
</head>
<body id="page-top">
     <div id="wrapper">
        <nav class="navbar align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0 navbar-dark">
            <div class="container-fluid d-flex flex-column p-0">
                @if(SignInManager.IsSignedIn(User))
                {
                    <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" asp-controller="Operations" asp-action="Index">
                        <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-wallet"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>Wallet</span></div></a>
                }
                else
                {
                    <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" asp-controller="Home" asp-action="Index">
                        <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-wallet"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>Wallet</span></div></a>
                }                
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Users" asp-action="Index" asp-route-control="AllUsers"><i class="fas fa-user"></i><span>
                                    Users
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Operations" asp-action="Index" asp-route-sortorder="desc">
                            <i class="fas fa-table"></i><span>
                                Operations
                            </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Accounts" asp-action="Index"><i class="fas fa-table"></i><span>
                            Accounts
                        </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="BankCards" asp-action="Index"><i class="far fa-credit-card"></i><span>
                                Cards
                            </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Currencies" asp-action="Index"><i class="far fa-money-bill-alt"></i><span>
                                Currencies
                            </span></a>
                        </li>
                    }
                    <li class="nav-item"><a class="nav-link" href="/api/swagger"><i class="far fa-file-code"></i><span>
                        Developer API
                    </span></a></li>
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-expand bg-white shadow mb-4 topbar static-top navbar-light">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle me-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                            <form asp-controller="Users" asp-action="Index" method="get" class="d-none d-sm-inline-block me-auto ms-md-3 my-2 my-md-0 mw-100 navbar-search">
                                <div class="input-group">
                                    <input class="bg-light form-control border-0 small" type="search" name="Keyword" placeholder="Search for Users by Keyword">
                                    <button class="btn btn-primary py-0" type="submit"><i class="fas fa-search"></i></button>
                                </div>
                            </form>                        
                                <ul class="navbar-nav flex-nowrap ms-auto">                   
                                    <li class="nav-item dropdown no-arrow">
                                        <div class="nav-item dropdown no-arrow">
                                            <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#">
                                                @if (User.Claims.ElementAt(6).Value == "True")
                                                {
                                                    <span class="text-danger"><strong>blocked:&nbsp;</strong> </span>
                                                }                                          
                                                <span class="d-none d-lg-inline me-2 text-gray-600 small">@User.Identity.Name</span>
                                                <img class="border rounded-circle img-profile" src="@Url.Content(User.Claims.ElementAt(5).Value)" width="32" height="32">
                                            </a>
                                            <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in" data-bs-popper="none">
                                                <a class="dropdown-item" asp-controller="Users" asp-action="Details" asp-route-id="@SignInManager.UserManager.GetUserId(User)">
                                                    <i class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Profile</a>                                               
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" asp-controller="Users" asp-action="Logout"><i class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Logout</a>
                                            </div>
                                        </div>
                                    </li>                           
                                </ul>                        
                        </div>
                    }
                </nav>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Copyright © Team 02 2023 - Wallet.Web - <a asp-area="" asp-controller="Home" asp-action="About">About</a></span></div>
                </div>
            </footer>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/chart.min.js"></script>
    <script src="~/js/bs-init.js"></script>
    <script src="~/js/theme.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>